### ISSUE TITLE
Identify Tool Does Not Respond

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Field-Tool#189]
Identify tool does not appear to be functional. If you click the button, nothing happens and if you click a point in the map, it still does not generate a response. 

![image](https://cloud.githubusercontent.com/assets/16919898/16493201/9e72168c-3eb2-11e6-8180-3c974e776e55.png)

**Comment by kanglu666** [comment]
currently the identify tool button is just s holder place . i will drop it now. will bring it back for future enhancement if needed

**Comment by leeensminger** [comment]
@kanglu666 needs to be able to identify base data - including contours, streams, parcels, etc. Please implement this update.

**Comment by leeensminger** [comment]
Per screenshare meeting - Identify tool will allow user to select "identify top-most layer", "identify all visible", "select a layer to identify".  These options will be housed in a new tab/panel on the left.

We will prioritize base data first, then NPDES business data /  feature service

**Comment by dhenry-KCI** [comment]
@kanglu666 :

Based on our internal GS conversation 07/27:

- We will prioritize and release base data "Identify" functionality.  NPDES business data will be a later release due to additional complexity.
- We will develop "Identify all visible", and "select a layer to identify".  Functionality to "identify top most layer" will not be developed at this time, due to additional complexity.  We will look to analyze and develop this within a later release/version.

**Comment by kanglu666** [comment]
identify tool updated, ready for testing in version 1.3 release
