### ISSUE TITLE
Pipe/Structure Inspection Issue

### ISSUE THREAD

**Issue by KCI-Ablowers** [leeensminger/DelDOT-NPDES-Field-Tool#372]
Most recent email I can find - 8/7/20 -

> Andrew,
> 
> Crews were able to sync this morning but are still noticing the same pipe inspection and structure inspection photo problem. When this happens, they also cannot see the IDs of their new features from the previous day.
> 
> Additionally, as an FYI which may or may not be related to issues we have been having lately but it seems like there are duplicate feature IDs in the database, which are auto-generated in the nightly script. It seems to be isolated primarily to June 12, 2020 but there are roughly 21 conveyances that have the same conveyance ID (1 corresponding to a historical feature that was migrated in from the old database and 1 corresponding to a new feature from June 12).
> 
> Please let me know if we can help in any way.
> 
> Thanks,
> Christina 

@kanglu666 we need to discuss and let @cstevenson1 know what we need from her to diagnose and debug.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 I was incorrect about the field tool update. Can you please provide a work area that is currently experiencing the issue so @kanglu666 can review?

**Comment by cstevenson1** [comment]
@KCI-Ablowers I would recommend you or Lu trying to recreate the problem in the field tool since he did not find anything last time we provided a work area. It's just a matter of creating a pipe inspection, syncing, letting the nightly script run, syncing, and seeing if that pipe inspection is still visible in the field tool. 

If you still need a work area, please let me know so I can coordinate with the field staff.

**Comment by KCI-Ablowers** [comment]
@kanglu666 I don't see an issue with Christina's suggestion above. We can discuss tomorrow (9/16/20)

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Lu will use the previously provided work area to debug. If additional information/data is needed we will let you know.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please install version 9.0 Prod from here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Tech_Services\LU\DelDotPROD\FieldTool9.0-prod_Delete WorkAreaToken_Added and test. @kanglu666 believes it may be a field tool version issue because of your original screenshots from here - V:\_RESOURCE_MANAGEMENT\Greater_Mid_Atlantic\Geospatial_Solutions\Staff\ANDREW\DelDOT\Pipe Inspection Sync Issue show v8.3. 

Lu reviewed the provided work area and was able to see both inspections - 
![Conveyance_0110067914](https://user-images.githubusercontent.com/35460336/96060157-bec10400-0e5d-11eb-924f-2a58b17181bf.png)
![Structure_0110072719](https://user-images.githubusercontent.com/35460336/96060158-bec10400-0e5d-11eb-9e7d-8b0a91a8d075.png)

From your email on 7/16/20 -

> In addition to the above, any pipe conveyance edited on 7/14 can be reviewed for debugging from the work area mentioned above. None of the 7/14 pipe inspections were visible in the field tool on 7/15 after syncing in the morning. If he deleted the work area and re-downloaded, the inspections came back.

Lu will test this workflow in the dev environment and update here.

**Comment by cstevenson1** [comment]
@KCI-Ablowers I just confirmed with field staff that they already have 9.0 on their device and that the issue is still happening. We even looked at the MVVM.exe in their folders, which has a date modified of 8/30/20. This issue has been going on since July and 9.0 wasn't released until the end of August, so it makes sense that my original screenshot would say 8.3. 

Were you able to reproduce the issue as I recommended? The work area we originally provided has already been reviewed by your team, which wasn't expected to be the problem since the data is there and syncing to the database. I would strongly recommend you try to recreate the problem. If you are unable to recreate the problem using a new fresh work area, then we will try a fresh install on all our devices and set up a screen share if it continues.

**Comment by cstevenson1** [comment]
@KCI-Ablowers just spoke with Bruce and he said to hold off on this until the underdrains are complete.

**Comment by KCI-Ablowers** [comment]
From @cstevenson1 on 11/13/20 -

> They even stated the pipe inspection issue we are currently having, did not appear to be a problem in this version of dev.

Keeping is open for now incase the issue should return after the switch over to the 2016 boxes and the new release of the Prod field tool.

**Comment by KCI-Ablowers** [comment]
@cstevenson1 Please review this issue or discuss with your field crews to see if it was addressed in the most recent version of Prod. You or I can close if it is fixed.

**Comment by cstevenson1** [comment]
@KCI-Ablowers confirmed with a few different people that they are no longer having the issue. Will close for now and re-open/create new bug if issues arise.
