### ISSUE TITLE
Lab Result parameters need to allow for ND

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#48]
All of the Lab Result Parameters need to allow for a value of "ND". 

![image](https://cloud.githubusercontent.com/assets/16919958/12918658/1842cb38-cf0e-11e5-929a-147e16d1bd8f.png)

**Comment by leeensminger** [comment]
@mjuber-kci What is "ND"?

Should users be able to enter the value ND in the text box, instead of a numerical value?  If yes, then the field will be changed to a Text/string field, so that users can enter a value like, "4.34", "10.1", "ND", etc.  What length should the text string be, to accommodate whatever number accuracy you want, and these ND values?

Like this? - 

![image](https://cloud.githubusercontent.com/assets/4103847/13034401/74d7d59e-d302-11e5-8c11-93c3fe32acfe.png)

**Comment by mjuber-kci** [comment]
Yes it should be changed to a text/string field. It should allow for possibly 10 characters.  ND means Not Detected. Having the ability to input "ND" into the database instead of a number also allow us to distinguish which parameters we tested for and which ones we did not. The lab does not use "0" as a result value, instead they report any value below the reporting limit as ND. In the new database, ND would represent these values and 0 would represent parameters that were not tested for.

**Comment by leeensminger** [comment]
Does this also apply to the parameter values for the sample which is collected by KCI field crews (in the Flow Char form)?

**Comment by mjuber-kci** [comment]
No, we do not use ND for any of the parameters for the field tests (in the Flow Char form). We would only need a max of 5 numerical characters for those values.

**Comment by leeensminger** [comment]
Lu this is updated in the database and pending loading by BC.  You can make adjustments as necessary.

**Comment by kanglu666** [comment]
updated, ready for testing in next release
