### ISSUE TITLE
Barrel Conveyance Inspection

### ISSUE THREAD

**Issue by mjuber-kci** [leeensminger/DelDOT-NPDES-Field-Tool#93]
Barrel Conveyances does not allow for inspection of individual pipes or "segments" within a barrel. The only options are inspecting each barrel individually (using the Barrel Inspections button circled in red) or inspecting the barrel conveyance as a whole (using the Inspection tab circled in blue). We need to have the ability to inspect each barrel or the individual segments like what was shown in the wireframes.

![image](https://cloud.githubusercontent.com/assets/16919958/13012284/9b5cb5da-d178-11e5-9ba4-ef755a80f0be.png)

Wireframe showing inspecting the barrel as a whole or the segments individually.

![image](https://cloud.githubusercontent.com/assets/16919958/13012315/c63b383a-d178-11e5-8ac6-ec717db7277e.png)

**Comment by leeensminger** [comment]
@mjuber-kci , to do an inspection or work order for a specific pipe segment, its necessary to exit the barrel conveyance workflow, and enter the Conveyance workflow.  Instead of selecting a Barrel Conveyance, select from Conveyance, and do the inspection or work order.

As we started developing this component, we had to modify the workflow a little bit from what was designed.  Users should generally be performing an inspection on the Barrel Conveyance as a whole, OR the individual pipe segment - and not both - therefore, this workflow should be workable.
